[package]
name = "brain-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brain-error = { path = "../brain-error" }
quote = "1.0.23"
proc-macro2 = "1.0.24"
regex = "1"
syn = { version = "1.0.109", features = ["full"] }
